# Для тех кто смотрит этот код, я понимаю что надо использовать secret для логинов и паролей. 
# Это демонстрация работы и для упраащения деплоя у вас и не парится с чуствительными данными указал в открытов виде в docker файлах
# TODO: hide sensitive data
version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=marketplace
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  marketplace:
    build: ./marketplace/
    container_name: marketplace
    command: bash /app/runserver.sh
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/marketplace
    depends_on:
      - db
  erpexch:
    build: ./exchange/
    container_name: erpexch
    command: bash /app/runserver.sh
    ports:
    - "8001:8001"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/marketplace
    depends_on:
      - db
      - marketplace
  celery:
    build: ./exchange/
    container_name: celery
    command: celery -A exchange worker  --loglevel=info
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/marketplace
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - marketplace
      - redis
      - erpexch
  redis:
    image: redis:alpine
    container_name: redis
  dashboard:
    container_name: flower
    build: ./exchange/
    command:  celery flower --port=5555
    ports:
      - 5555:5555
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/marketplace
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - marketplace
      - redis
      - erpexch
      - celery