# Для тех кто смотрит этот код, я понимаю что надо использовать secret для логинов и паролей. 
# Это демонстрация работы и для упраащения деплоя у вас и не парится с чуствительными данными указал в открытов виде в docker файлах
# TODO: hide sensitive data
version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=marketplace
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  marketplace:
    build: ./marketplace/
    container_name: marketplace
    command: bash /app/runserver.sh
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/marketplace
    depends_on:
      - db