# Generated by Django 4.0.7 on 2022-08-21 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_recipient', to=settings.AUTH_USER_MODEL)),
                ('sendler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_sendelr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=1000)),
                ('finish', models.BooleanField(default=False)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exchange')),
            ],
        ),
    ]
