# Generated by Django 4.0.7 on 2022-08-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_class', models.CharField(max_length=255)),
                ('name_data', models.CharField(max_length=255)),
                ('type_data', models.IntegerField(choices=[(0, 'xml'), (1, 'json'), (2, 'yaml'), (3, 'xls')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MappingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=255)),
                ('name_data', models.CharField(max_length=255)),
                ('mappint_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mappingclass')),
            ],
        ),
    ]
