# Generated by Django 4.0.7 on 2022-08-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mappingclass_mappingfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingfield',
            name='mappint_class',
        ),
        migrations.AddField(
            model_name='mappingfield',
            name='mapping_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='core.mappingclass'),
        ),
    ]
