# Generated by Django 4.0.7 on 2022-08-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_mappingfield_mappint_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedata',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='core.exchange'),
        ),
    ]
