name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd agora-exchange
            git pull
            docker-compose up -d --build
          host: ${{ secrets.SERVERIP }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
