name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVERIP }}  >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz -e "ssh"  ./ ${{secrets.USER}}@${{secrets.SERVERIP}}:~/agora-exchange/
      - name: Start docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVERIP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/agora-exchange/
            docker-compose up -d --build
